language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
install:
  - rm -rf public src package.json package-lock.json
services:
  - redis-server
  - postgresql
jobs:
  include:
    - stage: Deploy
      script:
        - './script/build.sh'
      deploy:
        provider: heroku
        api_key:
          secure: jDLZMsZxPqJGxDU9XQNO61A14zr51epnUlTmNPRfJnUjOzl0zQjWdLfVhM+9Wr2hIO1xIyukL6Vcuxb6xK7xik3FPhZX8kuH54iYfNVC48+EvsnPDA3iY+Bq7TRoSSLKYmwMcgp7iobHVCG7jm9vwu+srjqS+mHHPF9Zc1f4jgnH08c3JhgQzVp4Ep7t3wljiGPqhS620VI3eHB0Jmjx0FXl7ShDDd5NbOkbulfK/8AhvOOIjlnr2cx88Iw0Jku/XilS+0a1VbItwSyUc1Ew/B9hcFYwZwyOdh8VcuvnGy5nYEKyNv9KnxPSwrR/7mlVHatxIgGwNECSKE7pfl6PRFoueQAc7dFKGe4PkNsvbCt9MFzN3TvF5TuPSUKAon8RKFdXg0wcrF0PGU7+VTDJ53fcvMNPBcdKv2fYn1gPZm0x9h3QvHSkcBU6xmaiwynxLVNaBqhHaVMJ0msRC9KrlXJ3WTmFyFBpf1lcXxscHHP1hOPKgga7OhMqO0G9cXF2gYG5T0n8sWc00SlHWAQ+5DawcVu9t+cLYOhcHKkKB+ElzEHRFsNA/SD1uc6JPAQOc7oibdcxg9FbMbmS+ea7U70CpSfQExoMLv7BgJzNb1us3BmbRB82KPu25/VIuXyKO2WFOKGRBAO8/Oo7N7wHQq3/FacOHoSAF4yOtc7NrK0=
        skip_cleanup: true
        app: give-feedback
        run: restart
